### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#11]
This repo needs a license. I suppose we take the same license as for most other repos in oemof, GPL-3.0?

**Comment by p-snft** [comment]
Pick the most permissive, every author agrees to. Re-licensing to a less permissive one is easy.

**Comment by uvchik** [comment]
I would prefer MIT. See https://github.com/oemof/organisation/issues/50.

**Comment by jnnr** [comment]
I am ok with MIT.

**Comment by jnnr** [comment]
@uvchik  :heavy_check_mark: 
@ckaldemeyer   :heavy_check_mark: 
@FranziPl 
@jakob-wo :heavy_check_mark: 
@jnnr  :heavy_check_mark: 
@Pyosch   :heavy_check_mark: 

[6] All 
[5] MIT: @uvchik, @jnnr, @Pyosch, @ckaldemeyer, @jakob-wo

**Comment by uvchik** [comment]
I edited the list and added @Pyosch because of the pending PR #7

**Comment by jakob-wo** [comment]
> Re-licensing to a less permissive one is easy.

Why is that? 
I imagine it to be difficult to re-license a repo after having agreed on a permissive one. On one hand I expect heavy discussions if some contributers want a roll-back after some time. And on the other hand every one who starts including MIT-code now will be in trouble if later versions are released under a more restricted license. Don't you think so?

I am still not sure whether we should go along with MIT or GPL.

**Comment by p-snft** [comment]
> > Re-licensing to a less permissive one is easy.
> 
> Why is that?

It is possible to license additional contributions to a MIT codebase under e.g. LGPL and then to (re)distribute the new collection (as a whole) under LGPL. However, a given license cannot be revoked. So, whoever got the MIT-Licensed code can continue to use it. A well-known example is [Cedega](https://de.wikipedia.org/wiki/Cedega#Kritik): The software marketed a Software based on a MIT-licensed codebase without upstreaming the improvements. Consequently, the upstream project (Wine) changed to LGPL.

**Comment by uvchik** [comment]
It is not allowed or at least a grey zone to use solph, feedinlib, windpowerlib in other programs that do have a more permissive licence than the GPLv3. Therefore it is not useful to have a restrictive licence in a basic library. The GPLv3 could be useful for program which is not intended to be integrated by others.

I is my goal that oemof can be used as easy as possible to create energy models and to publish these models under any licence and not only the GPLv3.

**Comment by p-snft** [comment]
Adding to that: The Free Software Foundation, that authored the GPL, advices not to use it for libraries. Instead, they created the aforementioned LGPL, which allows free usage of the library (as a whole) also for e.g. MIT-licensed models. When you, @jakob-wo, dislike the idea that someone applies changes to oemof(-thermal) but does not grant the same freedoms as we do, the LGPL is what you want. However, while the use of oemof(-thermal) would be possible, this would still limit usability of oemof(-thermal) code fragments in other scientific projects.

**Comment by jakob-wo** [comment]
Thank you both, @p-snft and @uvchik, for your statements and explanations.

I do support to license this repo under MIT.

**Comment by p-snft** [comment]
@FranziPl: I misinterpreted your consent in https://github.com/oemof/organisation/issues/50 as one to thermal as well. I hope, this was Ok.
