### ISSUE TITLE
Outdated section 'Examples' in oemof.thermal’s documentation

### ISSUE THREAD

**Issue by MaGering** [oemof/oemof-thermal#116]
The list of available examples needs to be adjusted in the documentation:
https://oemof-thermal.readthedocs.io/en/latest/examples.html

After discussing this with @jnnr these two approaches emerged:
1. Adjusting the list of examples manually (now and every time there are changes)
2. Working with links to the components examples on GitHub and leaving the list of the specific examples out

Are there further suggestions?

**Comment by c-moeller** [comment]
done
