### ISSUE TITLE
Flake8 complains after I merged dev into a feature-branch

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof-thermal#118]
After I merged dev into features/absorption_chillers I get the following message from Travis CI complaining about flake8 rules :

```
$ flake8
./tests/test_constraints.py:31:40: E741 ambiguous variable name 'l'
```

1) Can we change that variable name in the respective module?
2) Do you know why that error did not come up when the respective commit of the dev was pushed but know it pops up in the feature-branch?
3) flake8 does not give me that message when I run flake8 localy but only when travis CI checks it online after I pushed it - what may be the reason for that?

**Comment by jnnr** [comment]
It seems that flake8 complains about variables named 'l' 'O' or 'I', as they can be easily confused or read as one or zero. I changed the name in a commit on your branch. I also did not get the error locally, I did not check why this is the case.

**Comment by jakob-wo** [comment]
@jnnr Thank you!
We should also adapt this in the dev brunch, right? If not I will have a merge conflict... and above all the problem with "l" in the dev brunch will remain.

**Comment by jnnr** [comment]
You don't have to adapt this in the dev branch - there will be no conflict if the same line has not changed in dev (it has not changed in dev). Just proceed with the PR and merge it when it is ready. After merging, the commit will apply to the dev branch as well.

**Comment by jakob-wo** [comment]
You are right - I was not aware of that.
Thanks again, you fixed the problem. 
Can I close this Issue or shall we leave it open until we figured out how we have to configure flake8 locally to get an error of that type? Btw me, I did not get an error locally neither.

**Comment by jnnr** [comment]
Might be that your local flake8 has another version than the remote. You could check that, e.g. here https://travis-ci.org/github/oemof/oemof-thermal/jobs/686461987#L187

 Would be good to close the issue soon.

**Comment by jakob-wo** [comment]
I do not find any indication of the remote flake8 version on that link.
However, the original problem has been solved, so we might close this issue.

**Comment by jnnr** [comment]
The link is specific to the line. You have to unfold at 185 "pip install -r tests/test_requirements.txt".
