### ISSUE TITLE
Readthedocs does not create apidocs

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#12]
It would be helpful if the docs on the api is built automatically, as in oemof/oemof:

https://github.com/oemof/oemof/tree/dev/doc/api

Edit: Locally, building the apidocs work. However, readthedocs fails. See below for an error log.

**Comment by uvchik** [comment]
You can use sphinx-apidoc locally and push the results to the repository. The result should look similar to what you see in oemof.

**Comment by FranziPl** [comment]
If I define a function with just one return value, the category "return type" is automatically created in the docstring. I have no idea, how to avoid it. Can you help me?

**Comment by jnnr** [comment]
I noticed that in readthedocs, there is a checkbox asking if you want to install the package using setup.py that was unchecked before. When I check it, readthedocs installs oemof and the dependencies into its virtualenv. As a consequence, the import error changes, but does not disappear:

> WARNING: autodoc: failed to import module 'thermal.compression_heatpumps_and_chillers' from module 'oemof'; the following exception was raised:
No module named 'oemof.thermal'

See the full log here:

https://readthedocs.org/api/v2/build/10077785%20%20.txt

**Comment by jnnr** [comment]
As a side note: Installing via setup.py triggers installing a lot of packages which takes extra time and resources. Would be putting oemof to autodoc_mock_imports a good way to avoid that?

**Comment by birgits** [comment]
@jnnr I had a look at it and the documentation didn't compile locally for me. I used the dev branch. Which one did you use?
I got it to compile when I changed the path in automodule to `.. automodule:: src.oemof.thermal.compression_heatpumps_and_chillers`. There might be a way to allow `.. automodule:: oemof.thermal.compression_heatpumps_and_chillers` but I'm not sure where that could be set. I also had to delete the csp and stratified_thermal_storage from the api doc, as these modules do not exist in the dev. After that it worked. Maybe that does the trick for rtd as well.

**Comment by jnnr** [comment]
> @jnnr I had a look at it and the documentation didn't compile locally for me. I used the dev branch. Which one did you use?

@birgits and I talked and found out that the reason why it did not compile locally because the package was not installed. With the package installed, everything works locally. I tried the same again on a pytho3.7 environment - still could not reproduce the error that shows in rtd. Is there anything else we can test to understand what is going wrong?

**Comment by gnn** [comment]
> I got it to compile when I changed the path in automodule to
> ```
> .. automodule:: src.oemof.thermal.compression_heatpumps_and_chillers`
> ```
> . [..]

That was a really nice comment, @birgits . It made me aware of the fact that there is a difference between building documentation based on an installed package versus doing it based on checked out sources. The `src` folder is only available in checked out sources, so when it works with that path, that's an indicator of the fact that you only have the local sources available and that they are not properly installed as a package. This prompted me to look at how things are done in `oemof.tabular` and there we are using a `docs/requirements.txt` file to install those requirements which are only necessary to build the documentation. As this includes the package at hand in it's most recent form, i.e. based on the checked out sources, this file has to include a `-e .` line at the minimum. Doing this and telling RtD about the `docs/requirements.txt` file in the "Advanced Settings" seems to fix the issue. If you do so, you can also leave the "Install Project" checkbox unticked.
Please have a look and doublecheck whether I'm correct.

**Comment by jnnr** [comment]
Thanks, @birgits and @gnn! That was very helpful.
