### ISSUE TITLE
We do not have a docs template for new components

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#13]
The documentation of the new components should be consistent across the different components. To get there, we need some kind of template. Here a first draft:

* Scheme of the component  (e.g. flow diagram).
* Description.
* Link to docstrings for equations (as e.g. https://oemof.readthedocs.io/en/stable/oemof_solph.html#extractionturbinechp-component).
* Insightful output graphics (the same as in the example).

For the docstrings, align along the existing docstring template of oemof/oemof (see this issue https://github.com/oemof/oemof/issues/597)

Please extend this description with your points!

**Comment by jakob-wo** [comment]
I propose to use a couple of subsections (sub-menu items). Have a look at the documentation of the module "Compressions Heat Pumps and Chillers" to get an impression.

In particular, I would like to draw your attention on the first subsection I would like to establish: "Motivation and possible application". Giving a reader the explanation why we actually developed this module and what we intended to use it for makes it much more ease to evaluate whether it is suitable or not for her/his own project.

**Comment by jnnr** [comment]
> I propose to use a couple of subsections (sub-menu items). Have a look at the documentation of the module "Compressions Heat Pumps and Chillers" to get an impression.

I like the idea of subsections. They give structure and make it easy to get an overview. I would propose different names for the headlines, though. "Motivation and possible application" seems to refer to the motivation of the devs that lead them to develop that piece of code. I would expect such a thing in a paper, but not in the documentation of a module.

I guess the reader wants to know: What is the idea of these tools and how can I use them? The goal is to give a concise description of what the user can expect from the module. I suggest:

**Scope**
"This module was developed to provide ... for energy system optimizations with oemof.solph."
To which kind of systems do these tools apply to?

**Concept**
Scheme
Description of the concept
Equations

**Usage**
Overview table of parameters
Code snippets
Link(s) to example(s)
Insightful output graphics

**References**
Citation(s), if the concept is adapted from the literature.

**Comment by jakob-wo** [comment]
> "Motivation and possible application" seems to refer to the motivation of the devs that lead them to develop that piece of code. 

In fact, that is my very intention. I want to tell people why we wrote that pieces of code. 

> I guess the reader wants to know: What is the idea of these tools and how can I use them? 

Definitely. I think telling people about our intention is a way to do so.

**Comment by jnnr** [comment]
I guess we are aiming for the same: The docs should lower access barriers and be transparent. Of course it is essential to communicate the intention behind a tool.

However, I would suggest to spare the reader the long story of the origin and the whole process of our efforts. Make a long story short. Tell them about the result they can see in front of them.

**Comment by jakob-wo** [comment]
> the long story of the origin and the whole process of our efforts

Well, I think we have a missunderstanding here....
The sentence (a single sentence!) that I suggested to describe the motivation is:

 For the module compressions_heat_pumps_and_chillers:

_"This module was developed to provide COP calculations based on temperatures for energy system optimizations with oemof.solph."_ 

Or in case of the CSP:

_"This module was developed to provide the heat of a parabolic trough collector based on temperatures and collectors location, tilt and azimuth for energy system optimizations with oemof.solph."_

I am still convinced that these sentences are very helpful and very often me myself I miss such a short description in "simple language".

But I wont keep pushing it if you really don't want it.

**Comment by jnnr** [comment]
Yes, these sentences are fine and helping. I just suggested to change the headlines (Motivation and possible application), as they remind more of a journal publication than a documentation. The headline _Scope_ seems more concise and gets to the point quicker, I think. The example sentences would fit very well under this headline. Would this combination be a good compromise, @jakob-wo ?

**Comment by jakob-wo** [comment]
> Would this combination be a good compromise?

Yes, a very good one! :)  
Thank you!

**Comment by c-moeller** [comment]
Is this issue solved with the unified headlines? Or is there some more work to do?

**Comment by jnnr** [comment]
In my view, this can be closed.
