### ISSUE TITLE
Example includes outdated warning/advice

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof-thermal#130]
The example stratified_thermal_storage/stratified_thermal_storage.py starts with the comment:

```
"""
For this example to work as intended, please use the not yet released oemof branch
https://github.com/oemof/oemof/tree/v0.3
that contains the new attributes for GenericStorage, `fixed_losses_absolute` and
`fixed_losses_relative`.
"""
```
oemof v0.3 has been released and the comment might be confusing.

In general I would prefere all examples worked with the same set of versions/distribution instead of special requierements one need to find out by reading the source code.

**Comment by jakob-wo** [comment]
This Issue will be dealt with in PR #135 .
Shall we move it to Milestone v0.0.4?

**Comment by jnnr** [comment]
No, this should be in v0.0.3, because it is a change related to the new oemof v0.4

**Comment by jnnr** [comment]
The docs also includes a warning that should be removed.
