### ISSUE TITLE
Release v0.0.3

### ISSUE THREAD

**Issue by c-moeller** [oemof/oemof-thermal#132]
I went through all the issues for v0.0.3 and chose only one assignee at a time so I know who the main responsible person is.

@oemof/oemof-heat 
1) Please look through it promptly and change it if I am wrong.
2) Please open a **PR** for each issue (if you haven't already done so), or even an empty one first
3) Remember to fill in the **Whats-new** file in the respective PR
4) There is also the possibility to get help from @MaGering. If that makes sense somewhere, join her as assignee (but not for all issues, please, because she already has a quite long todo list and I coordinate her tasks, i.e. everything will be also on my table... :-)
5) Deadline for merging PRs and closing issues: if possible **26.6**.

**Comment by c-moeller** [comment]
@oemof/oemof-heat I decided to do the release tomorrow, not today. So there is some time left to finish the open tasks. Please shift all issues you are not able to finish to v0.0.4 Thank you :-)

**Comment by c-moeller** [comment]
It's done :sunglasses: 
Thank you for your contributions!

https://oemof.org/2020/07/03/oemof-thermal-v0-0-3-amazing-absorption/
https://pypi.org/project/oemof.thermal/0.0.3/

Does anyone know, why I have to 'pip install oemof.thermal==0.0.3'? It does not work with 'oemof.thermal'. Hope there is nothing wrong. I thought always the last version will be catched.

One open todo is left:
* [x] Edit zenodo entry, see https://github.com/oemof/oemof-solph/wiki/Edit-Zenodo-entry

**Comment by uvchik** [comment]
Use 'pip install oemof.thermal --upgrade` if oemof.thermal is already installed.
