### ISSUE TITLE
Contradictory calculation of the chiller's quality grade

### ISSUE THREAD

**Issue by MaGering** [oemof/oemof-thermal#139]
I've been recently using the chiller model and wanted to calculate the quality grade for a specific chiller using the function calc_chiller_quality_grade().

I then realized that the calculation written in the docs differs from the one implemented in the function. According to the documentation I calculate the quality grade with Q_hot_nominal in the denominator. In the function however the denominator contains the nominal electric consumption instead of the heat flow out of the condenser.

Which one is the correct equation for the calculation of the quality grade?

**Comment by jakob-wo** [comment]
@MaGering: It has to be the nominal electric power consumtion, as it is implemented in the function! The mistake is in the docs. Thank you for pointing that out.

**Comment by jakob-wo** [comment]
I opend a PR and will fix it.

**Comment by jakob-wo** [comment]
It is fixed!

**Comment by MaGering** [comment]
I think there still is a mistake. Shouldn't it be T_low,nominal in the numerator of the main denominator?

Q_chilled,nominal / P_el / (**T_low,nominal** / (T_high,nominal - T_low,nominal))

**Comment by jakob-wo** [comment]
@MaGering you were absolutly right! Thank you for fixing it.
