### ISSUE TITLE
Tame solar thermal devices

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-thermal#152]
Solar thermal sources generated by the facades currently have a `fix` yield. This means, all of it has to go somewhere. It would prevent energy systems from being unsolvable because of heat overproduction, when it is seen as the maximum instead or if an excess heat `Sink` is automatically added.

PR #150 implements this by setting the yields as the `max`.

What do you think, @oemof/oemof-heat?

**Comment by c-moeller** [comment]
@p-snft This PR is done, isn't it? Can we close this issue?
And could you add a short line to the v0.0.4 WhatsNew-File?

**Comment by p-snft** [comment]
It's done, thanks.
