### ISSUE TITLE
What's New information on v0.0.3 release is missing in documentation

### ISSUE THREAD

**Issue by c-moeller** [oemof/oemof-thermal#160]
https://oemof-thermal.readthedocs.io/en/latest/whats_new.html

I have no idea why, since the file exists: https://github.com/oemof/oemof-thermal/blob/dev/docs/whats_new/v0-0.3.rst

@oemof/oemof-heat Can somebody help?

**Comment by jnnr** [comment]
The filename is different to the name of the file in docs/whats_new.rst. I will open a PR.
