### ISSUE TITLE
Docs: Non-intuitive order of chapters

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#167]
I suggest to change the order of the docs. In my view, it makes more sense to first explain the usage and then show the validation. This would be the proposed order:

Getting started
User's guide
Model validation
Theoretical considerations
Reference

It can be done quickly so it can be included in the upcoming release.

**Comment by FranziPl** [comment]
I am not sure about that. I think your order is intuitive, but the other one as well. Maybe I want to see the validation first, to decide, if I will use the component. So I am happy with both versions.

**Comment by jnnr** [comment]
> I am not sure about that. I think your order is intuitive, but the other one as well. Maybe I want to see the validation first, to decide, if I will use the component. So I am lucky with both versions.

Thanks for your opinion! I guess you can still decide which chapter to read first. But logically, at least how I understand it, the explanation of the concept of a component and how you apply it comes first before providing some evidence that it is valid when applied to real world data.

**Comment by c-moeller** [comment]
I agree with @jnnr 
I think the current order was not created on purpose.

**Comment by c-moeller** [comment]
There is also a docs issue in oemof/oemof: https://github.com/oemof/oemof/issues/67
I think we are not up-to-date with our Getting-started-section, but I think this is nothing we could solve within oemof-heat anymore.

**Comment by c-moeller** [comment]
order is fixed https://github.com/oemof/oemof-thermal/pull/169

**Comment by c-moeller** [comment]
See https://github.com/oemof/oemof-thermal/issues/171 for further tasks
