### ISSUE TITLE
oemof heat modelling: technogies that should be representable in future (to be implemented as classes (blocks) or via the network-logic)

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof-thermal#2]
On the last [user meeting](https://github.com/oemof/oemof/issues/241) we discussed different technologies that should be representable either by implementing them or by describing them in the network logic. There's also a research project coming which will extend oemof for heat modelling that probably starts next summer.

This issue is meant to provide an overview about the current state and future plans in terms of oemof heat modelling.

Here's the first suggestion for technologies that should be representable adequately within oemof:

- Heat sink
  - District heating networks / @ckaldemeyer
- Heat storage
  - Water heat storages (atmosperic and higher pressures) / @ckaldemeyer
  - Downhole heat exchanger heat storages / someone from RLI
- Peak load
   - Peak load boilers working with gas, oil, ... / @ckaldemeyer
- Power to heat
   - (Electrode) heating rods  / @ckaldemeyer
   - Heat pumps (having air/ground as heat source) / @birgits has some experience here
- CHP
  - Back-pressure turbines / @ckaldemeyer
  - Extraction turbines / @uvchik has adopted @simnh approach from HESYSOPT [in this PR](https://github.com/oemof/oemof/pull/248)
  - Motoric combined heat and power plants / @ckaldemeyer

Proposed methodology:

1.) The idea would be to use the [wiki](https://github.com/oemof/sandbox/wiki) to collect formulations (LP/MILP) from literature and discuss their pros and cons.
2.) Subsequently, the technologies can be represented with existing possibilities (network-logic) or within classes based on the literature formulations and results of the discussion.
3.) The [wiki](https://github.com/oemof/sandbox/wiki) could also be extended to an information source on how to model different technologies within oemof.

@uvchik : Did I forget anything?

**Comment by ckaldemeyer** [comment]
One thing I forgot:

We had the idea of thinking in "generic characteristics" of components rather than explicit formulations where possible.

Doing this, a component can have different real world represantations and different "simple" components can be combined to model more complex components via the network logic..

**Comment by ckaldemeyer** [comment]
I have created a [wiki page](https://github.com/oemof/sandbox/wiki/Overview-of-heat-technologies) now and will start to collect literature there.

**Comment by uvchik** [comment]
I would not use the wiki but the rst files. This makes it much easier to reuse the information later in the oemof documentation.

**Comment by ckaldemeyer** [comment]
> I would not use the wiki but the rst files. This makes it much easier to reuse the information later in the oemof documentation.

My comment was from December 2016 and I agree with you concerning the new purpose ;-)

**Comment by ckaldemeyer** [comment]
By the way there was a strong consense in renaming the repository using minuses so I just did it!

**Comment by uvchik** [comment]
> My comment was from December 2016 and I agree with you concerning the new purpose ;-)

:rofl:

**Comment by uvchik** [comment]
> By the way there was a strong consense in renaming the repository using minuses so I just did it!

Feel free it is just a first sketch....
