### ISSUE TITLE
Readme is (almost) empty

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#27]
There is no text in the README.rst yet. We should add a short description of the project so that the users know what to expect from this package.

**Comment by c-moeller** [comment]
Do we want do use this picture? If so, we only have to change oemof.solph to oemof.thermal.

![oemof_solph_komponente_v5](https://user-images.githubusercontent.com/8330132/70547572-64865100-1b71-11ea-9d24-6f8d08dd3751.png)

**Comment by jnnr** [comment]
I like the pictures of the components. However, I rather see this graphic as part of presentations and not so much as a helpful picture for users of a tool to understand what it can do for you. I had a look at different projects. Most of them do not have pictures in the readme. Pypsa is an exception - it shows some model results: https://github.com/PyPSA/PyPSA

**Comment by jnnr** [comment]
More important is a text that describes the package. It could be structured like this
* About
* Quickstart
* Documentation
* Contributing
* What's new
* License

**Comment by FranziPl** [comment]
I am not sure about the "Quickstart". It is also a collection of calculations, which can be used with other packages, so maybe this is not suitable. I am not sure, if we should skip it or if we should rename it and define, what is part of this section.
But I would agree to the rest of the structure.

**Comment by jnnr** [comment]
> I am not sure about the "Quickstart". It is also a collection of calculations, which can be used with other packages, so maybe this is not suitable. I am not sure, if we should skip it or if we should rename it and define, what is part of this section.

Thanks for your feedback. Quickstart would just comprise some few lines on how to install and how to import from packages. If you have time, have a look at the associated PR #28 and tell me what you think.
