### ISSUE TITLE
There are no tests

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#34]
We do not have any tests yet. It would be very helpful for developers to have some automatic tests. I suggest that we do the following: First, think about how reasonable tests for the package would look like. Then, the contributors to the different modules write some tests for the functions.

TODO

* [x] Write tests for solar_thermal_collector

**Comment by jnnr** [comment]
There are PRs underway that introduce tests. Leave this issue open until a test coverage metric is introduced.

**Comment by jakob-wo** [comment]
What about this Issue? Can we close it?

**Comment by jnnr** [comment]
There are no tests yet for the solar thermal collector.

**Comment by jakob-wo** [comment]
Of course, you're right! I somehow missed that package - sorry!

**Comment by jnnr** [comment]
No problem! Thanks for asking :)

**Comment by jnnr** [comment]
To get a detailed view of the parts of the code that are covered and which not, you can use the following command to generate an report in html form

`pytest --cov --cov-report html`
