### ISSUE TITLE
So far, there are only preprocessing functions

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#36]
So far and to my knowledge, the modules contain functions for preprocessing only. PR #16 introduces a function for allocating emissions in CHP. Maybe there are other situations in which postprocessing functions can help. We should discuss if this demands a change the structure of the modules or the docs.

**Comment by jakob-wo** [comment]
I would like to talk about the terminology first because I do not fully agree on your view that the modules would contain functions for preprocessing only. Preprocessing is what we intent to use these modules for (mainly as input for a oemof.solph component). But they partly can be used as stand-alone calculations as well and other users may use them completly different than we do. In that case the term _pre_-processing would not be appropiate, in my opinion.

**Comment by jakob-wo** [comment]
Regarding the function for allocating emissions in CHP (#16) I see a similar situation. I guess postprocessing is what you intent to use that function for. When I saw PR # 16 the first time I had another usage in mind: For an optimization I need to have the share of emissions allocated to the heat supply from a CHP to make sure this heat supply fullfulls requirements (e.g. limited emissions in a year). In that case the function for allocating emissions are used in preprocessing.

I suggest calling the functions _cululations_ - without post or pre :)

**Comment by jnnr** [comment]
Hey @jakob-wo, thanks for your comments! I guess that you are right - the modules for the different technologies collect functions that can be used to do calculations in different contexts, be it before an optimization, after, or independent from it. We could leave that open. So we have a better understanding of how the modules are organized. Thanks for helping to make that clearer.

 Do you think it would be helpful to write this in a few sentences into the docs? Apart from this, we could close this issue.

**Comment by jnnr** [comment]
How about this text on the index page of the docs, after Welcome to oemof.thermal's documentation!?

----

oemof.thermal is an oemof library with a focus on thermal energy technologies (heat/cool). Its original intention was to be used as a more specialized extension to the components in the optimization framework oemof.solph. However, some of its functions may be useful for their own. 

oemof.thermal is organized as follows:

For each technology that is covered, there is a module which holds a collection of useful functions. These functions can be applied to perform pre-calculations of an optimization model or postprocess optimization results. Besides, they can equally well be used stand-alone (totally independent from optimization).

For each module, there is a page that explains the scope of the module and the underlying concept. Mathematical symbols, their Usage and some sample results are shown. Lastly, notable references are listed for further information. 

Also, there are a couple of examples that can give an idea of how the functionality of oemof.thermal can be utilized.

----

Or as first text in 'getting started'?

**Comment by jakob-wo** [comment]
> How about this text on the index page of the docs

That's a great idea!

> These functions can be applied to perform pre-calculations of an optimization model or postprocess optimization results.

Here, I would additionally mention that the functions can even be used stand-alone (totally apart from optimization).

And yes, we can close this issue then.

**Comment by jnnr** [comment]
Ok, cool! Thanks for your feedback. I will include the text in getting started. Can you have a look at the PR?
