### ISSUE TITLE
There are mistakes in the strat. therm. storage docu

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof-thermal#40]
I found some mistake in die docu. (At least I think they are mistakes.)

1. The parameter table lists Gamma and Delta. As attribute names `fixed_losses` and `fixed_absolute_losses` are given. In the code I only find `fixed_losses_relative` and `fixed_losses_absolute` instead.

**Comment by FranziPl** [comment]
I think, we should open a PR, so we can make suggestions directly in the code.

**Comment by jnnr** [comment]
This issue seems resolved, can we close it?

**Comment by FranziPl** [comment]
Yes, we solved it with #42, so it can be closed.
