### ISSUE TITLE
Release v0.0.2

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#45]
We plan to have a second release of oemof.thermal around springtime. This brings the chance to release some some bug fixes and corrections of errors in the docs, but also new features. Please check your issues and PRs and assign them to the milestone if you think that that's a fit. 

These features are planned to be part of the new release:
* [x] Add tests,
* [x] Add facades for the new components,
* [x] Improve the docs,
* [x] for all new features, fixes, etc.: Remember to fill in the information in the whatsnew file. For open PRs this can happen in the respective PR. For closed PRs where we forgot to add the entry, this could happen in the release branch, as soon as we have one.
* [x] Before releasing: Test all examples, try if they work and behave nicely. Also check that results are ignored (.gitignore).

Please add if there is something missing.

**Comment by c-moeller** [comment]
> For closed PRs where we forgot to add the entry, this could happen in the release branch, as soon as we have one.

Please use the this branch for closed PRs: https://github.com/oemof/oemof-thermal/pull/87

**Comment by c-moeller** [comment]
Mission accomplished :partying_face: 
https://oemof.org/2020/04/30/oemof-thermal-v0-0-2-fancy-facades/
