### ISSUE TITLE
Apidocs for solar thermal collector is missing

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#48]
We should add the missing api documentation in api/oemof-thermal.rst
When doing that, we can adapt the order of the modules to alphabetical.

**Comment by jakob-wo** [comment]
@c-moeller: you are most familiar with that component and its documentation. Could you add the API-docu?

**Comment by jakob-wo** [comment]
I just noticed the module is called `flat_plate_collector.py` (instead of solar thermal collector). The section name in the documentation and the folder holding the examples of that module should be called the same way.

**Comment by jnnr** [comment]
> I just noticed the module is called `flat_plate_collector.py` (instead of solar thermal collector). The section name in the documentation and the folder holding the examples of that module should be called the same way.

Thanks for pointing to that. Should the module be called `solar_thermal_collector` or `flat_plate_collector`? I find the former more approachable, but I guess you know better. What's your preference, @FranziPl ?

**Comment by FranziPl** [comment]
I prefer the first one too. But somewhere in the documentation or docstring it should be pointed out that this only is valid for flat plate collectors.

**Comment by jnnr** [comment]
Ok, then let's go for it. If you like, you can take over the PR #54 and add a describing sentence to the docs.

**Comment by jnnr** [comment]
> I prefer the first one too. But somewhere in the documentation or docstring it should be pointed out that this only is valid for flat plate collectors.

@FranziPl: Can you please add the short sentence as you imagine it to the branch of #54, so we can merge the fix soon?

**Comment by jnnr** [comment]
@FranziPl: Thanks for approving #54. I merged it now to get this part finished. I actually thought you would add something according to what you proposed:

> But somewhere in the documentation or docstring it should be pointed out that this only is valid for flat plate collectors.

In the docs, it already says that it is a flat plate collector that is modelled. The docstring of the module does not specify this. So if you like, add a sentence in another PR.
