### ISSUE TITLE
The module name "chp" does not comply with the (unwritten) naming standard

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof-thermal#50]
First, the module name `chp.py` is an abrevation unlike the other names where "thermal_storage" is used instead of TES, and "concentrating_solar_power" instead of CSP. In my opinion it would be nice to rename the module `combined_power_and_heat.py`.

Second, we could even use the renaming to find a more appropiate and less missleading name for the module. "CHP" indicates that the module can be used to model the component CHP power plant because such power plant are often called CHP itself. I suggest we use a name that does not refer to a actual machine/unit - such as `cogeneration.py`.

Do you agree to renaming the modue `combined_power_and_heat.py`?
What do you think about changing the name to `cogeneration.py`?

**Comment by FranziPl** [comment]
What about emission_allocation_of_chp? too long?

**Comment by jnnr** [comment]
I like `cogeneration.py`, as it is shorter and is more general. Maybe `cogeneration_emission_allocation.py` would be fine, too? To decide, I would suggest to think about what developments are planned in the near future that could fit in this module, and choose a suitable name.

**Comment by FranziPl** [comment]
I'm fine with `cogeneration.py`, but I would prefere `cogeneration_emission_allocation.py` as the former implies, that it will calculate the generation and not the emission allocation.

**Comment by jnnr** [comment]
I thought about it again and it seems to me that cogeneration_emission_allocation is a bit to specific. It could describe the function in the module itself and does not give room for more. Hence I would vote for cogeneration.py.
