### ISSUE TITLE
Travis doesn't test all files in tests

### ISSUE THREAD

**Issue by FranziPl** [oemof/oemof-thermal#53]
Travis doesn't test all documents in the tests directory, but only the tests/test_functions.py file. 
Can we change this configuration to the whole directory? I would make a PR for that, but I didn't find the place, where it is defined.
@jnnr, can you help me with that? Thanks.

**Comment by jnnr** [comment]
Can you push the code so I can have a look? I cannot see any new file in your PR. Normally, it should be fine if your new test functions start with the word 'test'.

**Comment by jnnr** [comment]
It seems that the file has to be named starting with 'test_'.

**Comment by FranziPl** [comment]
Sorry, I pushed the wrong file, thats why, he didn't it. Now it is working
