### ISSUE TITLE
Schematic of components does not follow the same logic for all components

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#61]
The schematics of the 4 components in this package follow a different logic. Where the ones for stratified_thermal_storage and compression_heat_pumps_chillers show the energy/mass flows and balance in a diagram, the solar_thermal_collector and concentrating_solar_power rather show information flows.

If I remember correctly, we said that we would like to follow the former concept (energy/mass flows). In my opinion, this is useful to know what we are talking about. It makes it easier to understand the concept of the component that is to be represented. 

If you agree, this would mean that the collector and csp module would get new schematics in the next release.

Maybe, the information flow picture is helpful in its own right. It could then move further down in the text. Also, keep in mind that this might change when facades are implemented.

Also, the schematics of 

* [ ] concentrating solar power (@FranziPl),
* [ ] solar collector (@c-moeller) and 
* [x] stratified thermal storage  (@jnnr) resolved in #42 

do not have a caption. Please add a caption similar to the one in https://oemof-thermal.readthedocs.io/en/latest/compression_heat_pumps_and_chillers.html

**Comment by c-moeller** [comment]
Ah, I see I'm already in charge for the solar thermal collector. @FranziPl Do I find your template somewhere so that we can use the same style?

**Comment by FranziPl** [comment]
In the branch features/improve-docu-pics you find the new scheme. I didn't merge it yet, because I want to adapt the existing picture (block diagram) too, when the facade is done. But the scheme is ready.

**Comment by c-moeller** [comment]
@MaGering 
Thank you!
