### ISSUE TITLE
Example for storage investments only invests in energy, not power

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#63]
As the title says, the present example for investment in thermal storages only optimizes the height and therefore the max. thermal energy content of the storage, not the max. thermal power of charging/discharging.

Question: Is this a good idea, or is it more realistic to size the nominal power with the size? 

As far as I know, a rule of thumb is to size the storage in a way that it can provide its max. thermal power for ~ 6-8h. This would be an argument to rather provide a ratio when doing storage optimization. With this approach, one would have to set some costs for the investment in power, too.

What do you think, @oemof/oemof-heat? If we come to the conclusion that the latter is closer to reality, we might change the example.

**Comment by jakob-wo** [comment]
> Is this a good idea, or is it more realistic to size the nominal power with the size?

So far I have too little experience with real life storage design to tell wether it is interesting/usefull to couple the max thermal power with the max content. But either ways we should provide a option to model the storage with decoupled values.

**Comment by jnnr** [comment]
To conclude, the storage already provides these options:

1. Invest into nominal_storage_capacity and charging/discharging power with a fixed ratio
2. Invest into nominal_storage_capacity and charging/discharging power independently without a fixed ratio

> So far I have too little experience with real life storage design to tell wether it is interesting/usefull to couple the max thermal power with the max content. 

I have read a couple of times that storages are sized with a rule of thumb: The storage should be able to provide its peak thermal power for 6-7 hours. This is a case where the coupling would be used. If one does not want to use a rule of thumb and rather let the model decide, option 2. is the one to go.

The question is: Is there a situation where one wants to

3. invest into nominal_storage_capacity but leave charging/discharging power fixed?

This is not possible at the moment. Maybe it is ok to postpone it and implement it when it is needed.

**Comment by c-moeller** [comment]
The third one seems to me an unusual case in terms of thermal storages (but I am not an expert). I wonder if we do have this functionality within the oemof cosmos in general. For example in case of hydrogen/methanation this function might be useful, as you can set a fixed electrolyser/methanation unit but leave the storage capacity open. But for those scenarios you could also couple a transformer with a storage component.

**Comment by ChristophPelsLeusden** [comment]
In my opinion option 3 does not occur in practical applications for thermal storages. It would be of interest if charging/discharging power would drive the overall cost (as it does for the hydrogen example as Caro correctly mentioned). Thus, I do think it is OK to go with the options 1 and 2 only.

**Comment by c-moeller** [comment]
@jnnr Can we close this issue? I think this is now documented in the docstrings, isn't it?

**Comment by jnnr** [comment]
Yes, we can.
