### ISSUE TITLE
Tests for different modules are mixed in one test file

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof-thermal#78]
I just realized that the module `test_functions.py` holds tests for the modules `cogeneration.py` and `stratified_thermal_storage.py`.

I would prefere to have seperated test modules (one for each module) named after the module it is testing, e.g.  `test_compression_heatpumps_and_chillers.py` for the module `compression_heatpumps_and_chillers.py`.

This would have two advantages:
1) clear structure makes it easy to find tests belonging to one module
2) avoid merge conflicts (like in PR #72 ) when tests for different modules are written at the same time.

**Comment by jnnr** [comment]
Hi there, thanks for this issue!

A good test suite will comprise different kinds of tests. Unit tests, integration tests, etc. For oemof-solph, constraint tests play an important role, that are tests that check if the right lp-files are created when creating a component. We will introduce these kinds of tests together with the facades. 

It makes absolute sense to keep the tests tidy and sorted for a quick overview for any future developer. One way would be to have a test module for each module in the code. 

Until now, we only have unit tests for the functions (which are in the test module 'test_functions.py'. Soon, there will be other kinds of tests. To keep things tidy, I suggest to collect tests of code from different modules but the same kind of test in the same module. I suppose that merge conflicts will become more rare once we reach some good test coverage.
