### ISSUE TITLE
Release v0.0.2

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#82]
In this issue we plan the next release, scheduled for mid of March 2020.

* For all new features, fixes, etc.: Remember to fill in the information in the whatsnew file.

**Comment by c-moeller** [comment]
@oemof/oemof-heat Could you please go through all of your issues and PRs and add the v0.0.2 milestone in case they will be part of the next release? That would help me a lot for an overview. Thank you :slightly_smiling_face:

**Comment by jnnr** [comment]
Closed in favor of #45
