### ISSUE TITLE
'solar_thermal_collector' not included in '__init__.py'

### ISSUE THREAD

**Issue by ciaradunks** [oemof/oemof-thermal#83]
The import statement:

from oemof.thermal.solar_thermal_collector import flat_plate_precalc

is not working (v.0.0.1), with the following error being displayed:

Cannot find reference 'solar_thermal_collector' in '__init__.py'

**Comment by FranziPl** [comment]
I cannot reproduce the problem. If I compute the examples, which also uses `from oemof.thermal.solar_thermal_collector import flat_plate_precalc`, it works without an error message. 
I have no idea, what the problem is.

**Comment by jakob-wo** [comment]
It is just the module name that is wrong:

> from oemof.thermal.solar_thermal_collector import flat_plate_precalc

In the master-branch the module is called oemof.thermal.**flat_plate_collector** (not oemof.thermal.**solar_thermal_collector**)

@ciaradunks  what branch are you working on?

Honestly, I do not know why the module is renamed oemof.thermal.solar_thermal_collector in the dev-branch...

**Comment by ciaradunks** [comment]
I am currently in the developer branch of v0.0.1, and in this file: **oemof-thermal/examples/solar_thermal_collector/flat_plate_collector_example.py**, it uses the import statement: 

`from oemof.thermal.solar_thermal_collector import flat_plate_precalc`

@jakob-wo shall I just change it to oemof.thermal.flat_plate_collector then?

**Comment by c-moeller** [comment]
@MaGering can you have a look at this? I remember that you adapted the names.

**Comment by jakob-wo** [comment]
> I am currently in the developer branch of v0.0.1

Hi @ciaradunks, I am not sure if I understand you right but I think their is no such thing as a release v0.0.1 of the dev branch. v0.0.1 is a release of the master branch.

> shall I just change it to oemof.thermal.flat_plate_collector then?

I recommend to make sure that the examples are from the same branch (and commit) as the oemof.thermal version you are using.
For example: If you used `pip install oemof.thermal` to install oemof.thermal you will have the master branch (at release v0.0.1) installed. In that case you should make sure you are using the examples from the master branch. Here are two ways to do so:
 a) if the cloned oemof.thermal make sure you checkout the master branch when running the examples. 
b) if you download the examples (as zip) from github manually make sure to select the _master_ branch (default is _dev_ !) before.

Let me know if that solves the problem.

**Comment by ciaradunks** [comment]
Hey @jakob-wo, yeah that was the problem! I was actually in the master branch but using the developer examples.

Thanks for your help :)

**Comment by jakob-wo** [comment]
You are very welcome! :)
