### ISSUE TITLE
comments in gitignore file are too specific / too personalized

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof-thermal#85]
The gitignore file holds comments that are personalized for specific users:
```
# data from Franzi
CSP_data/
CSP_results/

# results
examples/flat_plate_collector/results/
```
I suggest either
a) to keep that structure but use git-alias to make identification more easily (Franzi --> FranziPl)
or
b) remove user names and list `CSP_data/` and `CSP_results/` under `# results`

Me personally, I prefere option b).

**Comment by jnnr** [comment]
A third way would be to use a common directory name for results for all examples, and add results/ to .gitignore. 

This would replace the entry "examples/flat_plate_collector/results/"


CSP_data seems to be orphaned and can be deleted from .gitignore. @FranziPl, what do you think?
