### ISSUE TITLE
Examples not clean

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#93]
Before the release, the examples should be polished so that they are easier to read. Skimming through some of them, I saw some typos and a different structure for all of them. As we should test them anyway before releasing, we could also take an hour to clean them up.

**Comment by jakob-wo** [comment]
Good idea!

Do you refer to all examples or could you name some specific that you noticed already?

**Comment by jnnr** [comment]
Mainly the ones that I did not write and did not review or use yet, which are csp and solar thermal collector. 

We could share the work and cross-review the examples. I could start with a review and list all the bits that can be improved which I would post in this issue. Then, these improvements could be applied to the examples so we reach a better standard.

What do you think?

**Comment by c-moeller** [comment]
> We could share the work and cross-review the examples. I could start with a review and list all the bits that can be improved which I would post in this issue. Then, these improvements could be applied to the examples so we reach a better standard.

I think this is a good approach, thanks for pushing this!  However, I would recommend, that the facades must be priority. So from my view, first we need all man and woman power with the facades, and after successfully finishing these, we could start the work on this issue. OK?

**Comment by jnnr** [comment]
> I think this is a good approach, thanks for pushing this! However, I would recommend, that the facades must be priority. So from my view, first we need all man and woman power with the facades, and after successfully finishing these, we could start the work on this issue. OK?

I fully agree.

**Comment by jnnr** [comment]
TODO:

* [x]  Order of imports (follow pep8)
* [x] Unify name of input data directory
* [x] Unify plot creation: Save example plots in /results, elsewhere or just plt.show()?
* [x] Some examples produce new files: Plots and lp-files. Would it be better if they would not?
* [x] Unify comments that show that a new part of the code starts
* [x] I propose to drop the word 'example' from all examples. It is clear from their location that they are examples and the filenames get shorter.
* [x] csp_plant_example.py and csp_plant_example_andasol.py give almost the same results. I did not    find a place where the difference is explained (e.g. in the docstring of the example).
* [x] csp_plant_example.py
  When plotting, matplotlib throws this warning:  
  `WARNING:matplotlib.legend:No handles with labels found to put in legend.`
* [x] stratified_thermal_storage.py
`python3.6/site-packages/pandas/plotting/_core.py:1161: UserWarning: Attempting to set identical bottom == top == 0.0 results in singular transformations; automatically expanding.
  ax.set_ylim(None, 0)`

**Comment by c-moeller** [comment]
Due to pressure of time I would suggest to shift this to v0.0.3

**Comment by jnnr** [comment]
* csp_plant_example.py
  When plotting, matplotlib throws this warning:  
  `WARNING:matplotlib.legend:No handles with labels found to put in legend.`

**Comment by jnnr** [comment]
> Due to pressure of time I would suggest to shift this to v0.0.3

If everybody applies the above list (or at least some of these points) to the examples they contributed, it should be a quick improvement.

**Comment by jnnr** [comment]
I am finished with my review. I tested all examples and they run (on my computer). I collected the list above with comments.

**Comment by c-moeller** [comment]
@jnnr did you open a PR for your changes? Or are they already merged? I cannot find a PR in the closed PRs.
@MaGering will work on the todos for the rest of the examples next week.

**Comment by jnnr** [comment]
> @jnnr did you open a PR for your changes? Or are they already merged? I cannot find a PR in the closed PRs.
I did not open a PR as I understood that you want to postpone it to the next milestone. Only collected the comments.

**Comment by c-moeller** [comment]
Ah ok, then I misunderstood your comments. I thougth that you already implemented these changes in your example. Then @MaGering will look at all examples and open a new PR :+1:

**Comment by MaGering** [comment]
Here is my proposition of unifying the comments:

- [x] Write first word in capital letter according to pep8 in all comments
- [x] Gather all paths at the beginning of the example after libraries import with the comment: ‚Set paths’
- [x] ‚Read input data‘ followed by "pd.read_csv(…)"
- [x] ‚Parameters for the precalculation’ followed by initialization of parameters in precalculation
- [x] ‚Precalculation‘ followed by calculation of e.g. COP (compression heat pumps and chillers), irradiance (CSP), u-value (stratified thermal storage) …
- [x] ‚Parameters for energy system‘ in case these parameters are gathered
- [x] ‚Create and solve the optimization model’ followed by "Model(energysystem)"
- [x] ‚Set up an energy system model‘  followed by implementation of the components of the energysystem
- [x] ‚Build the system and solve the problem‘ followed by "energysystem = solph.EnergySystem(timeindex=date_time_index)"
- [x] ‚Example plot‘ followed by the plot of the results
- [x] ‚Get results’ for saving results

Do you have further proposition or changes regarding the list above?
