### ISSUE TITLE
Inconsistant unit specification

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-thermal#99]
Citing @ciaradunks:

I’ve noticed that the ‘s_iso’ (thickness of isolation) variable is said to be in mm, but in the csv example file it is in m. And then in the function it looks like the input is in mm but then it gets converted to m in line 45 of the ‘calculate_storage_u_value’ function. In the csv file should it actually be in mm?

Thanks for noting this! Can you get an overview and make a proposol how to fix this, @MaGering?

**Comment by MaGering** [comment]
I've fixed that in the PR https://github.com/oemof/oemof-thermal/pull/43

'stratified_thermal_storage.csv' contained 0.05 m as a value for s_iso. I've corrected it to 50 mm.
